FROM nginx:1.25

COPY api.html \
     index.html \
     index.ipfs.html \
     /usr/share/nginx/html/

COPY api /usr/share/nginx/html/api

COPY ./nginx/nginx.conf.template /etc/nginx/templates/default.conf.template
