FROM node:20

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy only the necessary files
COPY server.js server.js
COPY public public

# Expose the port the app runs on
EXPOSE 8080

# Define environment variable
ENV NODE_ENV=production

# Start the app
CMD ["npm", "start"]
